attribute = "lightgrey"
keyword = "lightgrey"
"keyword.directive" = "lightgrey" # -- preprocessor comments (#if in C)
namespace = "lightgrey"
punctuation = "pastelgreen"
"punctuation.delimiter" = "pastelgreen"
operator = "lightgrey"
special = "blue"
"variable.other.member" = "pastelblue"
variable = "pastelgreen"
# variable = "lightgrey" # TODO: metavariables only
# "variable.parameter" = { fg = "pastelgreen", modifiers = ["underlined"] }
"variable.parameter" = { fg = "pastelgreen" }
"variable.builtin" = "mint"
type = "pastelblue"
"type.builtin" = "pastelblue" # TODO: distinguish?
constructor = "lightgrey"
function = "pastelblue"
"function.macro" = "lightgrey"
"function.builtin" = "pastelblue"
tag = "lightgrey"
comment = "mint"
constant = "pastelblue"
"constant.builtin" = "pastelblue"
string = "lightgrey"
"constant.numeric" = "pastelgreen"
"constant.character.escape" = "blue"
# used for lifetimes
label = "blue"

"markup.heading" = "lightgrey"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "lightgrey", modifiers = ["underlined"] }
"markup.link.text" = "lightgrey"
"markup.raw" = "lightgrey"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6f44f0"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { }
"ui.background.separator" = { fg = "darklightgrey" }
"ui.linenr" = { fg = "darklightgrey" }
"ui.linenr.selected" = { fg = "lightgrey" }
"ui.statusline" = { fg = "lightgrey", bg = "transparentgrey" }
"ui.statusline.inactive" = { fg = "pastelgreen", bg = "transparentgrey" }
"ui.popup" = { bg = "darkgrey" }
"ui.window" = { fg = "pastelgreen" }
"ui.help" = { bg = "pastelblue", fg = "darkgrey" }

"ui.text" = { fg = "pastelgreen" }
"ui.text.focus" = { fg = "pastelblue" }
"ui.text.inactive" = "pastelblue"
"ui.virtual" = { fg = "darklightgrey" }

"ui.virtual.indent-guide" = { fg = "darklightgrey" }

"ui.selection" = { bg = "lightgrey", fg = "darkgrey" }
"ui.selection.primary" = { bg = "pastelblue", fg = "darkgrey" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "pastelblue" }
"ui.cursor.match" = { fg = "#212121", bg = "pastelblue" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "pastelgreen" }
"ui.highlight" = { bg = "pastelgreen" }
"ui.highlight.frameline" = { bg = "#634450" }
"ui.debug" = { fg = "#634450" }
"ui.debug.breakpoint" = { fg = "pastelgreen" }
"ui.menu" = { fg = "pastelgreen" }
"ui.menu.selected" = { fg = "darkgrey", bg = "pastelblue" }
"ui.menu.scroll" = { fg = "pastelgreen", bg = "darklightgrey" }

"diagnostic.hint" = { underline = { color = "lightgrey", style = "curl" } }
"diagnostic.info" = { underline = { color = "delta", style = "curl" } }
"diagnostic.warning" = { underline = { color = "blue", style = "curl" } }
"diagnostic.error" = { underline = { color = "pastelgreen", style = "curl" } }

warning = "blue"
error = "pastelgreen"
info = "delta"
hint = "lightgrey"

[palette]
pastelblue = "#8CBCD5"
lightgrey = "#BEC3CC"
pastelgreen = "#6AA280"
darklightgrey = "#797c82"
darkgrey = "#233C46"
mint = "#85ab76"
blue = "#44848c"
delta = "#1f663b"

transparentgrey = "#233C46"

