attribute = "beige"
keyword = "beige"
"keyword.directive" = "beige" # -- preprocessor comments (#if in C)
namespace = "beige"
punctuation = "purple"
"punctuation.delimiter" = "purple"
operator = "beige"
special = "blue"
"variable.other.member" = "pastelblue"
variable = "purple"
# variable = "beige" # TODO: metavariables only
# "variable.parameter" = { fg = "purple", modifiers = ["underlined"] }
"variable.parameter" = { fg = "purple" }
"variable.builtin" = "mint"
type = "pastelblue"
"type.builtin" = "pastelblue" # TODO: distinguish?
constructor = "beige"
function = "pastelblue"
"function.macro" = "beige"
"function.builtin" = "pastelblue"
tag = "beige"
comment = "mint"
constant = "pastelblue"
"constant.builtin" = "pastelblue"
string = "beige"
"constant.numeric" = "purple"
"constant.character.escape" = "blue"
# used for lifetimes
label = "blue"

"markup.heading" = "beige"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "beige", modifiers = ["underlined"] }
"markup.link.text" = "beige"
"markup.raw" = "beige"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6f44f0"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { }
"ui.background.separator" = { fg = "darkbeige" }
"ui.linenr" = { fg = "darkbeige" }
"ui.linenr.selected" = { fg = "beige" }
"ui.statusline" = { fg = "beige", bg = "transparentgrey" }
"ui.statusline.inactive" = { fg = "purple", bg = "transparentgrey" }
"ui.popup" = { bg = "darkgrey" }
"ui.window" = { fg = "purple" }
"ui.help" = { bg = "pastelblue", fg = "darkgrey" }

"ui.text" = { fg = "purple" }
"ui.text.focus" = { fg = "pastelblue" }
"ui.text.inactive" = "pastelblue"
"ui.virtual" = { fg = "darkbeige" }

"ui.virtual.indent-guide" = { fg = "darkbeige" }

"ui.selection" = { bg = "beige", fg = "darkgrey" }
"ui.selection.primary" = { bg = "pastelblue", fg = "darkgrey" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "pastelblue" }
"ui.cursor.match" = { fg = "#212121", bg = "pastelblue" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "purple" }
"ui.highlight" = { bg = "purple" }
"ui.highlight.frameline" = { bg = "#634450" }
"ui.debug" = { fg = "#634450" }
"ui.debug.breakpoint" = { fg = "purple" }
"ui.menu" = { fg = "purple" }
"ui.menu.selected" = { fg = "darkgrey", bg = "pastelblue" }
"ui.menu.scroll" = { fg = "purple", bg = "darkbeige" }

"diagnostic.hint" = { underline = { color = "beige", style = "curl" } }
"diagnostic.info" = { underline = { color = "delta", style = "curl" } }
"diagnostic.warning" = { underline = { color = "blue", style = "curl" } }
"diagnostic.error" = { underline = { color = "purple", style = "curl" } }

warning = "blue"
error = "purple"
info = "delta"
hint = "beige"

[palette]
pastelblue = "#85ab94"
beige = "#d9c7a6"
purple = "#b75a75"
darkbeige = "#8a7e69"
darkgrey = "#34342c"
mint = "#85ab76"
blue = "#44848c"
delta = "#44848c"

transparentgrey = "#34342c"

